### ISSUE TITLE
두번째 프래그먼트 리스트 안나오는 문제

### ISSUE THREAD

**Issue by vkdlxh** [ohjjoa/MyNews#9]
NewService 인터페이스에 있는 getKeywordNews부분이 이상합니다.
```
@GET("v2/fragment_everything")
fun getKeywordNews(@Query("q") keyword: String): Call<NewsResponse>
```
API요청하는 Get 부분이 `v2/fragment_everything`로 바뀌어있네요.
(아마 everything을 fragment_everything로 일괄변경하시면서 같이 바뀐거 같습니다)

News Api사이트에서 Everything API를 어떻게 취득하고 있는지 확인하시고 바꿔보세요.

https://newsapi.org/docs/endpoints/everything

**Comment by ohjjoa** [comment]
고마웡
